openapi: 3.0.3
info:
  title: XCD Product APIs
  version: '1.0'
  description: >-
    The XCD Product APIs enables seamless integration with the XCD HR & Payroll
    application deployed on a client's Salesforce organization, facilitating HR
    operations such as leave management, expense creation, and timesheet
    submission. Designed for efficiency, the API supports both synchronous and
    asynchronous calls and is optimized for handling large datasets through bulk
    operations.
paths:
  /xcdio__Leave_API__c:
    post:
      tags:
        - Leave
      summary: Book Leave
      operationId: ''
      requestBody:
        description: Book Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookLeave'
            example:
              records:
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-01-10"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-01-12"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-02-05"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-02-06"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__Illness__c: "Other"
              response_fields: "xcdio__Leave_Request__c"
              asynchronous: "false"
              allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
              example:
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10Q100000kS97VIAS
                  Id: a29Q1000000t6zFIAQ
                  record_Sequence: 1
                - success: false
                  errors: ["Sorry, the new Leave/Absence request could not be created as the dates entered for the new Leave/Absence request coincides/overlap with the dates of an existing Leave/Absence. Please confirm the dates and try again for the Role(s):  Dev"]
                  xcdio__Leave_Request__c: null
                  Id: null
                  record_Sequence: 2
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
    patch:
      tags:
        - Leave
      summary: Edit & Cancel Leave
      operationId: ''
      requestBody:
        description: Edit & Cancel Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditLeave'
            example:
              records:
                - xcdio__Leave_request__c: "a10Q100000iqtztIAA"
                  xcdio__Approval_Status__c: "Cancelled"
                - xcdio__Leave_request__c: "a10Q100000iqtzsIAA"
                  xcdio__Approval_Status__c: "Recalled"
              asynchronous: "false"
              allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
              example:
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10Q100000kS97VIAS
                  Id: a29Q1000000t6zFIAQ
                  record_Sequence: 1
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10S900000Mqng1IAB
                  Id: a28S9000000TCAgIAO
                  record_Sequence: 2
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
components:
  schemas:
    BookLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: Array of leave request records to be created which is described in BookLeaveRecordDetail schema. Every XCD API has a threshold number of records which can be passed in a single synchronous request defined in "XCD Integration API" custom metadata. The number of records in an asynchronous request can be upto 10,000.
          items:
            $ref: '#/components/schemas/BookLeaveRecordDetail' 
        response_fields:
          type: string
          description: Comma separated list of fields in the API Object. Any new field can be added in the API object and dynamically queried using this field. 
          example: xcdio__Leave_Request__c or xcdio__Leave_Request__c, xcdio__Approval_Status__c
        asynchronous:
          type: string
          description: Request execution context. Synchronous requests will give response as part of the same request. Asynchronous request return a single batch_Id for the entire array which can be further queried for the request status and other fields. 
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: Allow partial leave records to be created if one or more of the records array is having any validation error. 
          
    BookLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_Category__c:
          type: string
          enum:
            - Annual Leave
            - Sick Leave
          description: The category of leave defined in XCD HRMS
          example: Annual Leave
        xcdio__Employee_Details__c:
          type: string
          description: Salesforce record id of the employee for whom the leave is to be booked. 
          example: a29Q1000000t6zFIAQ
        xcdio__Start_Date__c:
          type: string
          format: date
          description: Leave start date.
          example: '2025-01-10'
        xcdio__Start_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: Leave start slot.  
          example: All Day for full day, or PM if the leave starts from second half of the day. 
        xcdio__End_Date__c:
          type: string
          format: date
          description: Leave end date.
          example: '2025-01-10'
        xcdio__End_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: Leave end slot.
          example: All Day for full day, or AM if the leave is until first half of the day. 
        xcdio__Illness__c:
          type: string
          enum:
            - Back & neck
            - Chest & respiratory
            - Covid-19 confirmed
            - Covid-19 suspected
            - Covid-19 self-isolating
            - Diabetes
            - Eyes, ear, nose, mouth
            - Genito-urinary
            - Heart
            - Infection
            - Musculo-skeletal
            - Neurological
            - Pregnancy
            - Stomach
            - Stress
            - Other
          description: Applicable for sickness only. The enum values may vary depending on client customisations. 
          example: Others
          
    BookLeaveApiResponseSuccess:
      type: object
      properties:
        success:
          type: boolean
          example: "true"
          description: The status of the leave request record in the request array. 
        errors:
          type: array
          items:
            type: string
          example:  []
        xcdio__Leave_Request__c:
          type: string
          example: a10Q100000kS97VIAS
          description: Salesforce record id of the leave request. 
        Id:
          type: string
          example: a29Q1000000t6zFIAQ
          description: Salesforce record id of the api object record.
        record_Sequence:
          type: integer
          description: Sequence number of the record provided in the request array. 
          example: 1
          
    BookLeaveApiResponseFailure:
      type: object
      properties:
        success:
          type: boolean
          description: The status of the leave request record in the request array. 
          example: "true"
        errors:
          type: array
          items:
            type: string
          example:  []
          
    EditLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: Array of leave request records to be edited which is described in EditLeaveRecordDetail schema. Every XCD API has a threshold number of records which can be passed in a single synchronous request defined in "XCD Integration API" custom metadata. The number of records in an asynchronous request can be upto 10,000.
          items:
            $ref: '#/components/schemas/EditLeaveRecordDetail' 
        asynchronous:
          type: string
          description: Request execution context. Synchronous requests will give response as part of the same request. Asynchronous request return a single batch_Id for the entire array which can be further queried for the request status and other fields. 
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: Allow partial leave records to be created if one or more of the records array is having any validation error. 
    
    EditLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_request__c:
          type: string
          description: Salesforce record id of the leave request to be edited or canceled. 
          example: a10Q100000iqtztIAA
        xcdio__Approval_Status__c:
          type: string
          example: Cancelled
servers:
  - url: https://{mydomain}.my.salesforce.com/services/apexrest/xcdio/xcdapi/v1.0
    variables: {}
tags:
  - name: Leave
    description: 'Book, edit and cancel leave in XCD'
